query FindAllArticles {
  articles: findAllArticles {
    id
    articleId
    published
    releaseDate
    updateDate
    title
    emoji
    topicIcons {
      displayName
      icon
    }
    typeIcon {
      displayName
      icon
    }
    markdown
    html
    relations {
      articleId
      published
      releaseDate
      title
      emoji
      type
      topicIcons {
        displayName
      }
    }
  }
  length: countAllArticles
}
query FindMoreArticles($current: String!) {
  articles: findMoreArticles(current: $current) {
    articleId
    published
    releaseDate
    title
    emoji
    type
    topicIcons {
      displayName
    }
  }
}
query FindArticle($articleId: String!) {
  article: findArticle(articleId: $articleId) {
    id
    title
    articleId
    emoji
    type
    topics
    published
    releaseDate
    updateDate
    markdown
    html
    allTopics {
      displayName
      name
    }
  }
}
