query Post {
  allArticles: findAllArticles {
    articleId
    published
    releaseDate
    updateDate
    title
    emoji
    topicIcons {
      icon
      displayName
    }
    typeIcon {
      icon
      displayName
    }
    body
    relations {
      articleId
      published
      releaseDate
      title
      emoji
      type
      topicIcons {
        displayName
      }
    }
  }
}
