import { ArticleList, Heading, PageFrame } from 'components';
import { Zenn } from 'types/common';
import { sortByDate } from 'utils/common';
import { Head } from 'utils/next';
import { Fragment as _ } from 'react';
import pages from '../../../assets/scss/pages/Topics.module.scss';
import { useMount } from 'hooks';

const data = [
  {
    title: 'Zenn',
    articles: sortByDate('desc', [
      {
        id: 'zenn',
        releaseDate: new Date(2020, 8, 10),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '📘',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 10),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '🍋',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 1, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 1, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
    ]),
  },
  {
    title: 'TypeScript',
    articles: sortByDate('desc', [
      {
        id: 'zenn',
        releaseDate: new Date(2020, 8, 10),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '📘',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 10),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '🍋',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 1, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 1, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
    ]),
  },
  {
    title: 'React',
    articles: sortByDate('desc', [
      {
        id: 'zenn',
        releaseDate: new Date(2020, 8, 10),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '📘',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 10),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '🍋',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 1, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 1, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
    ]),
  },
  {
    title: 'Next.js',
    articles: sortByDate('desc', [
      {
        id: 'zenn',
        releaseDate: new Date(2020, 8, 10),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '📘',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 10),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '🍋',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 1, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 1, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
    ]),
  },
  {
    title: 'Vue.js',
    articles: sortByDate('desc', [
      {
        id: 'zenn',
        releaseDate: new Date(2020, 8, 10),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '📘',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 10),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '🍋',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 1, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 1, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
    ]),
  },
  {
    title: 'Nuxt.js',
    articles: sortByDate('desc', [
      {
        id: 'zenn',
        releaseDate: new Date(2020, 8, 10),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '📘',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 10),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '🍋',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2021, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 1, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 1, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 31),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn', 'TypeScript'],
      },
      {
        id: 'zenn',
        releaseDate: new Date(2020, 4, 11),
        title: 'Zennと自分のサイトで記事を同時投稿できるようにしてみた',
        emoji: '💻',
        type: 'tech',
        topics: ['Zenn'],
      },
    ]),
  },
];

export default function Topics() {
  const isMounted = useMount();
  return (
    <>
      <Head>
        <title>LeMoN | Topics</title>
      </Head>
      <PageFrame sectionClass={`${pages.topics} ${isMounted && pages.mounted}`}>
        <>
        <Heading rank={2} text="All Topics" className={pages.heading} />
          {/* {data.map((value: { title: string; articles: Zenn[] }, i: number) => (
            <_ key={i}>
              <ArticleList type="related" data={value.articles} display={4} className={pages.articles} />
              <hr />
            </_>
          ))} */}
        </>
      </PageFrame>
    </>
  );
}
