query About {
  titles: findTitle(page: "about") {
    text
    section
    icon
  }
  sentences: findSentence(page: "about") {
    text
    section
  }
  info: findList(name: "info", section: "profile") {
    list {
      title
      icon
    }
  }
  feelingProud: findImage(name: "feeling proud") {
    data
  }
  front: findListBySection(section: "front") {
    name
    list {
      title
    }
  }
  back: findListBySection(section: "back") {
    name
    list {
      title
    }
  }
  others: findListBySection(section: "others") {
    name
    list {
      title
    }
  }
}
