query clientBlog($displayNum: String!) {
  articles: findArticles(latest: false, displayNum: $displayNum) {
    id
    releaseDate
    title
    emoji
    type
    topicIcons {
      displayName
    }
  }
}
