query Post {
  titles: findTitle(page: "post") {
    text
    section
  }
  allArticles: findAllArticles {
    id
    releaseDate
    updateDate
    title
    emoji
    topicIcons {
      icon
      displayName
    }
    typeIcon {
      icon
      displayName
    }
    body
    relations {
      id
      releaseDate
      title
      emoji
      type
      topicIcons {
        displayName
      }
    }
  }
}
