query Topics {
  titles: findTitle(page: "topics") {
    text
    section
  }
  topics: findAllTopics {
    displayName
    icon
    allArticles {
      id
      releaseDate
      title
      emoji
      type
      topicIcons {
        displayName
      }
    }
  }
}
